MONO_HLSB: int
MONO_VLSB: int
GS2_HMSB: int


class FrameBuffer:
    def __init__(self, buffer: bytearray, width: int, height: int, format: int) -> None: ...
    def fill(self, color: int) -> None: ...
    def text(self, text: str, x: int, y: int, color: int) -> None: ...
    def hline(self, x: int, y: int, width: int, color: int) -> None: ...
    def vline(self, x: int, y: int, height: int, color: int) -> None: ...
    def line(self, x1: int, y1: int, x2: int, y2: int, color: int) -> None: ...
    def rect(self, x: int, y: int, width: int, height: int, color: int) -> None: ...
    def fill_rect(self, x: int, y: int, width: int, height: int, color: int) -> None: ...
